[HMA-4865] - Headline Card View
hmrc/ios-swiftui-components pull request #15
Opened 2021-11-09 11:48 UTC by chrisbirch

https://user-images.githubusercontent.com/3192947/140918825-f749a184-64d1-4cc4-98ae-de2e5b832833.mov

2021-11-09 11:59 UTC, paulb00th requested changes
Looks great - just a few nits from me

2021-11-09 11:59 UTC, paulb00th commented on SUICompanionApp/SUICompanionApp/Examples/ExampleImages.swift
> +        var uiImage: UIImage {
This doesn't seem to be used anywhere else in the PR

2021-11-09 11:59 UTC, paulb00th commented on SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift
> +                        Text("TODO: This example is meant to be an inset view, see none swift ui version", style: .body)
```suggestion
                        Text("TODO: This example is meant to be an inset view, see non-SwiftUI version", style: .body)
```

2021-11-09 13:34 UTC, paulb00th approved these changes

2021-11-09 15:19 UTC, tendai-moffatt requested changes

2021-11-09 15:19 UTC, tendai-moffatt commented on SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift
> +                Components.Organisms.HeadlineCardView(
As discussed - lets lose this example until we make the [IconButtonView Component](https://jira.tools.tax.service.gov.uk/browse/HMA-4860)

2021-11-09 15:19 UTC, tendai-moffatt commented on Sources/SUIComponents/Atoms/Button+HMRC.swift
> +    case secondary(padding: CGFloat = .spacer16, icon: Image? = nil)
As discussed - lets lose this until we make the [IconButtonView Component](https://jira.tools.tax.service.gov.uk/browse/HMA-4860)

2021-11-09 15:19 UTC, tendai-moffatt commented on Sources/SUIComponents/Atoms/Button+HMRC.swift
> +            case let .secondary(padding, image):
As discussed - lets lose this until we make the [IconButtonView Component](https://jira.tools.tax.service.gov.uk/browse/HMA-4860)

2021-11-09 15:19 UTC, tendai-moffatt commented on Sources/SUIComponents/Atoms/Button+HMRC.swift
> +    let image: Image?
As discussed - lets lose this until we make the [IconButtonView Component](https://jira.tools.tax.service.gov.uk/browse/HMA-4860)

2021-11-09 15:19 UTC, tendai-moffatt commented
Looks good apart from the [IconButtonView Component](https://jira.tools.tax.service.gov.uk/browse/HMA-4860) issue we discussed.

2021-11-10 10:16 UTC, tendai-moffatt approved these changes

2021-11-16 11:43 UTC, merged