Various Fixes
hmrc/ios-swiftui-components pull request #21
Opened 2021-11-19 14:43 UTC by chrisbirch

[HMA-4857] Fixes inset view layout
[HMA-4860] Icon Button view styling fixes
[HMA-4860] Icon Button view accessibility fixes
[HMA-4861] Dynamic Colours

2021-11-19 14:45 UTC, paulb00th approved these changes

2021-12-01 17:31 UTC, paulb00th requested changes
Looks good - one nit

2021-12-01 17:31 UTC, paulb00th commented on Sources/SUIComponents/Molecules/HeadlineCardView.swift
> +                            .accessibility(label: Text("\(title), heading"))
why twice?

2022-02-11 14:22 UTC, closed without merging

2022-02-11 14:22 UTC, chrisbirch commented
Duplicate